// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoH2x6CEGM71JXcoC0qUXnhWzIDnnflos',
    appId: '1:797389601181:android:afcfee8c19958f3a7d5774',
    messagingSenderId: '797389601181',
    projectId: 'movaka',
    storageBucket: 'movaka.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3zLNCLjSv9pILSaOuquZtB17pRFVmiDc',
    appId: '1:797389601181:ios:ca2126b4b14a103d7d5774',
    messagingSenderId: '797389601181',
    projectId: 'movaka',
    storageBucket: 'movaka.firebasestorage.app',
    iosBundleId: 'com.example.movakaApps',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE34k7xi19pvuvFMMbdVDtQ6YPWm6N-R4',
    appId: '1:797389601181:web:43b36b80752688b17d5774',
    messagingSenderId: '797389601181',
    projectId: 'movaka',
    authDomain: 'movaka.firebaseapp.com',
    storageBucket: 'movaka.firebasestorage.app',
    measurementId: 'G-Q27JRX7J60',
  );

}